import os


class Config:
    SECRET_KEY = os.getenv("SECRET_KEY")

    SQLALCHEMY_DATABASE_URI = os.getenv("SQLALCHEMY_DATABASE_URI")
    SQLALCHEMY_TRACK_MODIFICATIONS = bool(int(os.getenv("SQLALCHEMY_TRACK_MODIFICATIONS")))
    SQLALCHEMY_COMMIT_ON_TEARDOWN = bool(int(os.getenv("SQLALCHEMY_COMMIT_ON_TEARDOWN")))
